// Owner-editable puzzle content. Only the recording remains to be supplied.
// Asset paths are relative to act-2/. See CONTENT.md.
export const content = {
  flashlight: {
    code: "spooky",
  },
  jigsaw: {
    photo: "assets/jigsaw-photo.jpg",
    alt: "Together among hanging lights",
    columns: 6,
    rows: 8,
  },
  weighing: {
    objects: [
      {
        id: "bell",
        name: "Brass bell",
        image: "assets/scale-objects.png",
        sprite: 0,
        value: "2",
        position: 4,
      },
      {
        id: "feather",
        name: "Feather",
        image: "assets/scale-objects.png",
        sprite: 1,
        value: "7",
        position: 8,
      },
      {
        id: "shell",
        name: "Seashell",
        image: "assets/scale-objects.png",
        sprite: 2,
        value: "4",
        position: 3,
      },
      {
        id: "acorn",
        name: "Acorn",
        image: "assets/scale-objects.png",
        sprite: 3,
        value: "6",
        position: 1,
      },
      {
        id: "quartz",
        name: "Quartz",
        image: "assets/scale-objects.png",
        sprite: 4,
        value: "9",
        position: 6,
      },
      {
        id: "spool",
        name: "Spool of thread",
        image: "assets/scale-objects.png",
        sprite: 5,
        value: "1",
        position: 5,
      },
      {
        id: "coin",
        name: "Copper coin",
        image: "assets/scale-objects.png",
        sprite: 6,
        value: "8",
        position: 2,
      },
      {
        id: "spoon",
        name: "Silver spoon",
        image: "assets/scale-objects.png",
        sprite: 7,
        value: "3",
        position: 7,
      },
    ],
  },
  audio: {
  forwardRecording: null,
  backwardRecording: "assets/reversed.mp3",
  code: "1055",
},
  bananas: {
    wordList: "assets/english.txt",
    drawSequence: null, // Shuffle the full bunch anew on every playthrough.
  },
  dictionary: {
    clue: "A word, phrase, or sequence that reads the same forwards and backwards.",
    target: "palindrome",
    pages: [
      {
        number: 214,
        words: [
          "acorn",
          "actor",
          "address",
          "adventure",
          "anchor",
          "angle",
          "answer",
          "apple",
        ],
      },
      {
        number: 215,
        words: [
          "arch",
          "autumn",
          "balance",
          "balloon",
          "basket",
          "beacon",
          "bell",
          "bicycle",
        ],
      },
      {
        number: 216,
        words: [
          "blanket",
          "blossom",
          "bottle",
          "bridge",
          "cabin",
          "candle",
          "canvas",
          "canyon",
        ],
      },
      {
        number: 217,
        words: [
          "cascade",
          "castle",
          "cedar",
          "circle",
          "cloud",
          "compass",
          "copper",
          "corner",
        ],
      },
      {
        number: 218,
        words: [
          "crystal",
          "curtain",
          "dawn",
          "desert",
          "diamond",
          "dictionary",
          "distance",
          "door",
        ],
      },
      {
        number: 219,
        words: [
          "dream",
          "drift",
          "dusk",
          "echo",
          "edge",
          "ember",
          "engine",
          "envelope",
        ],
      },
      {
        number: 220,
        words: [
          "evening",
          "feather",
          "fence",
          "fern",
          "field",
          "flame",
          "flower",
          "forest",
        ],
      },
      {
        number: 221,
        words: [
          "fountain",
          "frame",
          "frost",
          "garden",
          "gate",
          "glass",
          "globe",
          "golden",
        ],
      },
      {
        number: 222,
        words: [
          "grain",
          "gravity",
          "green",
          "grove",
          "guest",
          "harbor",
          "harmony",
          "heart",
        ],
      },
      {
        number: 223,
        words: [
          "hedge",
          "hinge",
          "hollow",
          "honey",
          "horizon",
          "hour",
          "image",
          "ink",
        ],
      },
      {
        number: 224,
        words: [
          "insect",
          "island",
          "ivory",
          "jacket",
          "jasmine",
          "jewel",
          "journey",
          "judge",
        ],
      },
      {
        number: 225,
        words: [
          "kettle",
          "key",
          "kind",
          "kingdom",
          "kitchen",
          "ladder",
          "lake",
          "lantern",
        ],
      },
      {
        number: 226,
        words: [
          "lattice",
          "lavender",
          "leaf",
          "letter",
          "library",
          "light",
          "linen",
          "lock",
        ],
      },
      {
        number: 227,
        words: [
          "machine",
          "marble",
          "meadow",
          "melody",
          "memory",
          "metal",
          "mirror",
          "mist",
        ],
      },
      {
        number: 228,
        words: [
          "moon",
          "morning",
          "moss",
          "needle",
          "nest",
          "night",
          "north",
          "note",
        ],
      },
      {
        number: 229,
        words: [
          "number",
          "oak",
          "object",
          "ocean",
          "olive",
          "orbit",
          "orchard",
          "order",
        ],
      },
      {
        number: 230,
        words: [
          "origin",
          "outline",
          "owl",
          "page",
          "paint",
          "palindrome",
          "paper",
          "passage",
        ],
      },
      {
        number: 231,
        words: [
          "pattern",
          "pebble",
          "pencil",
          "petal",
          "phrase",
          "picture",
          "pine",
          "place",
        ],
      },
      {
        number: 232,
        words: [
          "planet",
          "plant",
          "pocket",
          "poem",
          "point",
          "pond",
          "portrait",
          "position",
        ],
      },
      {
        number: 233,
        words: [
          "prism",
          "promise",
          "pulse",
          "puzzle",
          "quartz",
          "queen",
          "question",
          "quiet",
        ],
      },
      {
        number: 234,
        words: [
          "quilt",
          "quiver",
          "quote",
          "rabbit",
          "rain",
          "rainbow",
          "raven",
          "reading",
        ],
      },
      {
        number: 235,
        words: [
          "reflection",
          "ribbon",
          "ridge",
          "river",
          "road",
          "room",
          "rose",
          "rotation",
        ],
      },
      {
        number: 236,
        words: [
          "route",
          "sail",
          "salt",
          "sand",
          "scale",
          "scarlet",
          "scroll",
          "season",
        ],
      },
      {
        number: 237,
        words: [
          "seed",
          "shadow",
          "shape",
          "shell",
          "shelter",
          "shimmer",
          "shore",
          "signal",
        ],
      },
      {
        number: 238,
        words: [
          "silver",
          "sky",
          "slate",
          "sleep",
          "smoke",
          "snow",
          "sound",
          "south",
        ],
      },
      {
        number: 239,
        words: [
          "spark",
          "speech",
          "spiral",
          "spool",
          "spring",
          "square",
          "stairs",
          "star",
        ],
      },
      {
        number: 240,
        words: [
          "steam",
          "stone",
          "story",
          "string",
          "summer",
          "sun",
          "sunrise",
          "sunset",
        ],
      },
      {
        number: 241,
        words: [
          "surface",
          "switch",
          "symbol",
          "symmetry",
          "table",
          "target",
          "temple",
          "thread",
        ],
      },
      {
        number: 242,
        words: [
          "threshold",
          "thunder",
          "tide",
          "tile",
          "timber",
          "time",
          "tower",
          "trail",
        ],
      },
      {
        number: 243,
        words: [
          "tree",
          "triangle",
          "tunnel",
          "turn",
          "twilight",
          "umbrella",
          "uncle",
          "under",
        ],
      },
      {
        number: 244,
        words: [
          "union",
          "unity",
          "valley",
          "value",
          "velvet",
          "verse",
          "vessel",
          "view",
        ],
      },
      {
        number: 245,
        words: [
          "violet",
          "voice",
          "voyage",
          "wall",
          "water",
          "wave",
          "weight",
          "wheel",
        ],
      },
      {
        number: 246,
        words: [
          "whisper",
          "white",
          "window",
          "wing",
          "winter",
          "wire",
          "wish",
          "witness",
        ],
      },
      {
        number: 247,
        words: [
          "wood",
          "word",
          "world",
          "wreath",
          "yarn",
          "year",
          "yellow",
          "yew",
        ],
      },
      {
        number: 248,
        words: [
          "yield",
          "yonder",
          "young",
          "youth",
          "zeal",
          "zebra",
          "zenith",
          "zero",
        ],
      },
      {
        number: 249,
        words: ["zigzag", "zinc", "zipper", "zone", "zoo"],
      },
    ],
  },
  symbolB: "☷",
  actThreeCode: "crash",
  actThreeUrl: "../act-3/",
};
