export const WORD_BANK = [
    { word: "ESCAPE", message: "I'm still counting our escape as a success. You were impressive with how quickly you solved some of those puzzles!" },
    { word: "BIBLE", message: "I appreciate how naturally your faith shows up in your life. It's one of the things I admire most about you." },
    { word: "CHERRY", message: "Official verdict of fresh cherry pancakes: Pending. I'm looking forward to making them with you. 🍒" },
    { word: "FARKLE", message: "The inspiration behind Laurdle! I remembered you mentioning that you played Farkle on your phone, and it got the wheels turning to build something special for you." },
    { word: "SCONE", message: "A throwback to our first date. It's sweet looking back at where this started, and I've really loved getting to know you. 😊" },
    { word: "CLIMB", message: "Our first activity together. I really appreciated you stepping out of your comfort zone to share that experience with me." },
    { word: "BRIDGE", message: "We walked through it four weeks after you said we'd have to come back to it sometime. I love that a little comment from our first date became a real memory." },
    { word: "BURGER", message: "The legendary Farm Boy burger deal. It still makes me smile that you tried kombucha just because I love it, even after hearing it tastes bad." },
    { word: "BOARD", message: "You put up a good fight at The Round Table. Your Bananagrams skills are impressive! Rematch soon?" },
    { word: "FUDGE", message: "I loved our car picnic with your favourite cake ☺️" },
    { word: "SHELL", message: "Or should it be shell x2? 😉🍨" },
    { word: "VACUUM", message: "We can make this a blue job 😉" },
    { word: "WINDOW", message: "A necessity over our kitchen sink." },
    { word: "MUSIC", message: "You have a beautiful voice! I love singing in the car with you and learning your favourite songs." },
    { word: "FAMILY", message: "I love how much you love your family. I can't wait to meet them and for you to meet mine." },
    { word: "HEART", message: "You have a beautiful heart, and I feel blessed to keep getting to know it." },
    { word: "STRIKE", message: "You got a strike (1), a spare (2), broke 100 (3), won a game (4), and you wanted a fifth (too cute). You looked good doing it!" },
    { word: "DINER", message: "The food wasn't great, but the company was perfect. I love that we wished another couple a happy anniversary right before starting our own. ❤️" },
    { word: "SUPPLY", message: "The magic chicken supply lives on. More for you today ❤️" },
    { word: "SMILE", message: "You have a stunning smile. Sometimes I try to make you laugh just so I can see it 😉" },
    { word: "CHIPS", message: "Handfuls of chocolate chips? Plain Ruffles? The chocolate chips in the banana bread? I'll go with the baker 🥰" },
    { word: "CHALK", message: "I found chalk on everything after our climbing date, but I loved every second with you." },
    { word: "BROWN", message: "Apparently kindergarten Kaden's favourite colour" }
];
