export const WORD_BANK = [
    { word: "ESCAPE", message: "I'm still counting our escape as a success. You were impressive with how quickly you solved some of those puzzles!" },
    { word: "BIBLE", message: "I appreciate how naturally your faith shows up in your life. It's one of the things I admire most about you." },
    { word: "CHERRY", message: "Official verdict of fresh cherry pancakes: Pending. I'm looking forward to making them with you. 🍒" },
    { word: "FARKLE", message: "The inspiration behind Laurdle! I remembered you mentioning that you played Farkle on your phone, and it got the wheels turning to build something special for you." },
    { word: "SCONE", message: "A throwback to our first date. It's sweet looking back at where this started, and I've really loved getting to know you. 😊" },
    { word: "CLIMB", message: "Our first activity together. I really appreciated you stepping out of your comfort zone to share that experience with me." },
    { word: "BRIDGE", message: "We walked through it four weeks after you said we'd have to come back to it sometime. I love that a little comment from our first date became a real memory." },
    { word: "BURGER", message: "The legendary Farm Boy burger deal. It still makes me smile that you tried kombucha just because I love it, even after hearing it tastes bad." },
    { word: "BOARD", message: "You put up a good fight at The Round Table. Your Bananagrams skills are impressive! Rematch soon?" },
    { word: "FUDGE", message: "I loved our car picnic with your favourite cake ☺️" },
    { word: "SHELL", message: "Or should it be shell x2? 😉🍨" },
    { word: "VACUUM", message: "We can make this a blue job 😉" },
    { word: "WINDOW", message: "A necessity over our kitchen sink." },
    { word: "MUSIC", message: "You have a beautiful voice! I love singing in the car with you and learning your favourite songs." },
    { word: "FAMILY", message: "I love how much you love your family. I can't wait to meet them and for you to meet mine." },
    { word: "HEART", message: "You have a beautiful heart, and I feel blessed to keep getting to know it." },
    { word: "STRIKE", message: "You got a strike (1), a spare (2), broke 100 (3), won a game (4), and you wanted a fifth (too cute). You looked good doing it!" },
    { word: "DINER", message: "The food wasn't great, but the company was perfect. I love that we wished another couple a happy anniversary right before starting our own. ❤️" },
    { word: "SUPPLY", message: "The magic chicken supply lives on. More for you today ❤️" },
    { word: "SMILE", message: "You have a stunning smile. Sometimes I try to make you laugh just so I can see it 😉" },
    { word: "CHIPS", message: "Handfuls of chocolate chips? Plain Ruffles? The chocolate chips in the banana bread? I'll go with the baker 🥰" },
    { word: "DRIVES", message: "I love our drives together. I find myself hoping for red lights just to get a little more time with you." },
    { word: "LIGHT", message: "You bring so much light into the little moments. I'm thankful for you and for the way your faith shines through your life." },
    { word: "GIFTS", message: "Having you in my life has been one of the sweetest gifts of this year. ❤️" },
    { word: "HOURS", message: "Hours with you feel like minutes, and it never feels like enough. ❤️" },
    { word: "THEME", message: "Today starts a themed week: some of my favourite things about you. First up: you are genuinely beautiful, inside and out." },
    { word: "GENTLE", message: "One of my favourite things about you is your gentleness. You have such a soft and caring heart, but there is real strength in the way you carry yourself and choose kindness." },
    { word: "JOYFUL", message: "One of my favourite things about you is your joy. I love the way you laugh, get excited, sing in the car, and bring sweetness into ordinary moments." },
    { word: "CARED", message: "You wrote that you're glad to be cared for by me, and that meant more to me than you probably realized.<br><br>One of my favourite things about you is how deeply you care for me and the people around you. It makes it very easy to want to care for you, encourage you, and make you feel loved.<br><br>So today, let the one who cares so deeply be cared for too ❤️" },
    { word: "THIRTY", message: "30 days of Laurdle ❤️ What started as a little idea to make you smile has become one of my favourite parts of each day.<br><br>One of my favourite things about you is the way you make little thoughtful things feel meaningful. Thinking of words, memories, and messages for you has become such a sweet daily rhythm, and I'm really glad I get to keep making this for you." },
    { word: "EFFORT", message: "One of my favourite things about you is the care and effort you put into the things that matter. I know how much you've poured into these report cards, and I can't wait to celebrate you being done tonight ❤️" },
    { word: "GRACE", message: "One of my favourite things about you is the grace you show people, even when situations are difficult. You have such a steady and caring way of trying to do what is right." },
    { word: "CHALK", message: "I found chalk on everything after our climbing date. Not sure climbing won you over, but you definitely won me over by stepping so willingly into something that wasn't really your thing just to be with me ❤️" },
    { word: "TRUST", message: "This weekend made me really grateful for the trust we're building.<br><br>I loved the way we could laugh, talk deeply, be honest about where we're at, and feel safe with each other. Getting to know your heart has been such a gift to me ❤️" },
    { word: "JUDAH", message: `Judah calling you "Tito's Lauren" was the cutest thing ever 🥹<br><br>Between inviting you to Japan and wanting to come to Canada for chicken nuggets at Bob Donald's with you, I think you may already be his best friend 🥰<br><br>It was so nice how quickly they warmed up to you. You have such a gentle and welcoming presence that helps people feel safe with you so naturally.` },
    { word: "PORCH", message: `You put this word in my head and I haven't been able to get it out 😉<br><br>Do I even need to explain this one? 😘` },
    { word: "JAPAN", message: "I'm so excited to explore with you, introduce you to Jazmin and her family, have endless fun with the kids, and watch you experience a place that's special to me.<br><br>It feels really sweet that we get to dream about something like this together and actually make it real ❤️" },
    { word: "PAINT", message: "I'm so excited to see how our ceramics turned out 🥰Painting them with you was such a fun part of an already perfect weekend." },
    { word: "NUGGET", message: "Judah already warmed up to you so quickly, but finding out that you like chicken nuggets too sealed the deal: best friends 🥹<br><br>“Lauren likes chicken nuggets too? Come to Japan to eat them with me.”<br><br>It makes me so happy thinking about you meeting them. I can't wait for them to experience the joy, care, and gentleness you have with kids ❤️" },
    { word: "SERVE", message: "One of the things I admire about you is how naturally you show up to serve others.<br><br>You spent yesterday morning helping at the work bee, and today you're back in Guelph to serve in kids min. Even in a full weekend, you still choose to give your time, energy, and care to people around you.<br><br>I love seeing the way your faith shows up in how you live ❤️" },
    { word: "SELFIE", message: "I've been loving all the selfies of you 😍<br><br>I love getting little glimpses of your day and seeing your beautiful face.<br><br>My photos have been filling up with pictures of you, and I'm definitely not complaining ❤️" },
    { word: "SHIRT", message: "I was a casual Germany fan before, but after seeing you in that shirt, I'm rooting for them to go all the way 😍<br><br>My parents thought they were just giving you something to wear for the game, but they accidentally gave me a gift too.<br><br>It was hard to focus on making the pizza and playing Sequence 😉" },
    { word: "THROW", message: "You started off with 3 points, then hit a bullseye on your second throw! 🎯<br><br>How are you so good at everything? It was very impressive and very attractive 😍" },
    { word: "PROUD", message: "You've poured so much care, patience, prayer, and effort into your students this year. I'm so proud of the teacher you are and the way you love your students so well.<br><br>You've made a huge difference, and it was noticed by leadership and felt by your students. I'm incredibly proud of you ❤️" },
    { word: "PICNIC", message: "We finally did it! No picnic bag, no blanket, and no salad dressing... but I had the most important part: you 🥰<br><br>We don’t need a perfect setup to have a perfect picnic ❤️" },
    { word: "BROWN", message: "Apparently kindergarten Kaden's favourite colour" }
];
